# These are supported funding model platforms

open_collective: # https://
ko_fi: https://ko_fi.com/stirnas
buy_me_a_coffee: https://buymeacoffee.com/devilishious
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
